language: go

sudo: false

go:
  - 1
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.x

notifications:
  email: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_script:
  - echo $PATH
  - echo $GOPATH
  - go version
  - go env
  - go get -v -t ./qr/...
  - go get github.com/mattn/goveralls

script:
  - make test
  - goveralls -coverprofile=coverage.out -service travis-ci